#define P_HAST 1
#define P_METHOD_NAMES 1

#define DEBUG_PRINT_EARLY_MODULE 0

#define DEBUG_MSG 1
#define DEBUG_CALLBACKS 1
#define DEBUG_PRINT_FINAL_MODULE 1


#define BACKEND_INITIAL_COMPILATION_SUCCESS_MSG 1
#define BACKEND_INITIAL_LLVM 1

#define DEBUG_MODULE_NAME_UPDATES 1
