sudo: required
dist: trusty

language: cpp

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja-build
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - ruby
      - openjdk-7-jdk
      - rsync
      - xorg-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=debug -GNinja
  - ninja setup
  - ninja

script:
  - ./tools/tests
  - ./tools/gnur-make check
