dist: trusty

language: cpp

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  - CHECK=check BUILD=release
  - CHECK=check-devel BUILD=debug
  - CHECK=check-recommended BUILD=release

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      env: CHECK=check BUILD=release
    - os: osx
      env: CHECK=check-devel BUILD=debug
    - os: osx
      env: CHECK=check-recommended BUILD=debug

addons:
  apt:
    packages:
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - rsync
      - xorg-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD .
  - make setup
  - make -j4

script:
  - ./tools/tests
  - TEST_MC_CORES=3 ./tools/gnur-make $CHECK

cache:
  - ccache
