sudo: required
dist: trusty

language: cpp

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  - TESTS=debug
  - TESTS=devel
  - TESTS=recommended

matrix:
  exclude:
    - os: osx
      env: TESTS=devel
    - os: osx
      env: TESTS=recommended
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - ninja-build
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - ruby
      - openjdk-7-jdk
      - rsync
      - xorg-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - if [[ "$TESTS" == "debug" ]]; then cmake -DCMAKE_BUILD_TYPE=debug -GNinja; else cmake -DCMAKE_BUILD_TYPE=release -GNinja; fi
  - ninja setup
  - ninja

script:
  - ./tools/tests
  - if [[ "$TESTS" == "devel" ]]; then ./tools/gnur-make check-devel; fi
  - if [[ "$TESTS" == "recommended" ]]; then ./tools/gnur-make check-recommended; fi
